<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    '2ee654cc7bb0eeea0995d765f2dd491f' => $vendorDir . '/myclabs/deep-copy/src/DeepCopy/deep_copy.php',
    '359bac5a3690a64e90623ade41484378' => $vendorDir . '/mpdf/mpdf/src/functions.php',
);
