<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'WCCartPDF\\setasign\\Fpdi\\' => array($vendorDir . '/setasign/fpdi/src'),
    'WCCartPDF\\Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'WCCartPDF\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src'),
    'WCCartPDF\\Mpdf\\PsrLogAwareTrait\\' => array($vendorDir . '/mpdf/psr-log-aware-trait/src'),
    'WCCartPDF\\Mpdf\\PsrHttpMessageShim\\' => array($vendorDir . '/mpdf/psr-http-message-shim/src'),
    'WCCartPDF\\Mpdf\\' => array($vendorDir . '/mpdf/mpdf/src'),
    'WCCartPDF\\DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
);
